### ISSUE TITLE
properly activate conda on Windows when using UDFs & fix reading Conda config

### ISSUE THREAD

**Issue by fzumstein** [xlwings/xlwings#1090]
Just using a **conda** installed numpy and importing numpy into the module with the UDF will fail currently if there are no PATH env vars set, see: #954 

Also: Config doesn't write/read Conda Base and Conda Env correctly because of casing.

**Comment by Guoliang2019** [comment]
Does this mean that making changes to PATH is the only option to allow udf to use numpy?
Thank you

**Comment by fzumstein** [comment]
no, this has been fixed and released.

**Comment by Guoliang2019** [comment]
thank you for reply, and sorry to bother you again. I still cannot import numpy in udf/macro python file.
the following is the config info under file xlwings.conf
"USE UDF SERVER","False"
"DEBUG UDFS","False"
"UDF MODULES","Excel_Macro"
"PYTHONPATH",""
"INTERPRETER","C:\Users\fzhan\Anaconda3\python.exe"
"CONDA BASE","C:\Users\fzhan\Anaconda3\Library\bin"

is there anything wrong with this setting? 

I attached the conda info and error I got if they help. 
[xlwings_conda_env.txt](https://github.com/xlwings/xlwings/files/3244321/xlwings_conda_env.txt)

Thank you so much

**Comment by fzumstein** [comment]
You'll always need both conda base and env, so if you're using the base env, use `base` for your `Conda Env`.

**Comment by fzumstein** [comment]
also, set `Interpreter` to nothing or `python` and Change `Conda Base` to `C:\Users\fzhan\Anaconda3`

**Comment by Guoliang2019** [comment]
Thank you for the reply. However, I still got the following error message.
![image](https://user-images.githubusercontent.com/48146575/58768557-40ff9f80-856b-11e9-80d5-7cf930a7f107.png)
I can find the dll file under folder "C: C:\Users\fzhan\Anaconda3" .  
![image](https://user-images.githubusercontent.com/48146575/58768614-14985300-856c-11e9-85e8-9e16632c5cd2.png)

Thank you so much for the continuous reply. Greatly appreciated. 
The following is my xlwings.conf and my conda info --envs
"USE UDF SERVER","False"
"DEBUG UDFS","False"
"UDF MODULES","Excel_Macro"
"PYTHONPATH",""
"CONDA BASE","C:\Users\fzhan\Anaconda3"
"CONDA ENV","base"
"INTERPRETER",""


conda info --envs
base                  *  C:\Users\fzhan\Anaconda3
Py2                      C:\Users\fzhan\Anaconda3\envs\Py2

**Comment by fzumstein** [comment]
Looking at your error, I think what you were experiencing wasn't an xlwings issue but a conda issue: https://stackoverflow.com/questions/41859939/python-pandas-missing-required-dependencies-numpy-1  So fix that and revert back to the config you had (remove both conda configs). seems like for now you'll need to setup the base env via the interpreter directly as you had it. this should be fixed to also work they way I told you but I will open a separate issue for that

**Comment by Guoliang2019** [comment]
Thank you. For now, I would create a new env to let xlwings use. Look forward to the fix. Thank you
